services:
  db_primary:
    image: postgres:16
    container_name: postgres_primary
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_primary:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 2s
      retries: 10

  migrate_primary:
    image: migrate/migrate
    depends_on:
      db_primary:
        condition: service_healthy
    volumes:
      - ./auth-provider/server/migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${DB_USER}:${DB_PASSWORD}@db_primary:5432/${DB_NAME}?sslmode=disable",
        "up",
      ]
    restart: "no"

  db_local_a:
    image: postgres:16
    container_name: postgres_local_a
    restart: always
    environment:
      POSTGRES_USER: ${DB_LOCAL_A_USER}
      POSTGRES_PASSWORD: ${DB_LOCAL_A_PASS}
      POSTGRES_DB: ${DB_LOCAL_A_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_local_a:/var/lib/postgresql/data

  db_local_b:
    image: postgres:16
    container_name: postgres_local_b
    restart: always
    environment:
      POSTGRES_USER: ${DB_LOCAL_B_USER}
      POSTGRES_PASSWORD: ${DB_LOCAL_B_PASS}
      POSTGRES_DB: ${DB_LOCAL_B_NAME}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_local_b:/var/lib/postgresql/data

volumes:
  postgres_data_primary:
  postgres_data_local_a:
  postgres_data_local_b:
