// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/groups": {
    params: {};
  };
  "/groups/:id": {
    params: {
      "id": string;
    };
  };
  "/users": {
    params: {};
  };
  "/users/:id": {
    params: {
      "id": string;
    };
  };
  "/apps": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/groups" | "/groups/:id" | "/users" | "/users/:id" | "/apps";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/" | "/groups" | "/groups/:id" | "/users" | "/users/:id" | "/apps";
  };
  "routes/_app._index.tsx": {
    id: "routes/_app._index";
    page: "/";
  };
  "routes/_app.groups.tsx": {
    id: "routes/_app.groups";
    page: "/groups" | "/groups/:id";
  };
  "routes/_app.groups._index.tsx": {
    id: "routes/_app.groups._index";
    page: "/groups";
  };
  "routes/_app.groups.$id.tsx": {
    id: "routes/_app.groups.$id";
    page: "/groups/:id";
  };
  "routes/_app.users.tsx": {
    id: "routes/_app.users";
    page: "/users" | "/users/:id";
  };
  "routes/_app.users._index.tsx": {
    id: "routes/_app.users._index";
    page: "/users";
  };
  "routes/_app.users.$id.tsx": {
    id: "routes/_app.users.$id";
    page: "/users/:id";
  };
  "routes/_app.apps.tsx": {
    id: "routes/_app.apps";
    page: "/apps";
  };
  "routes/_app.apps._index.tsx": {
    id: "routes/_app.apps._index";
    page: "/apps";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/_app": typeof import("./app/routes/_app.tsx");
  "routes/_app._index": typeof import("./app/routes/_app._index.tsx");
  "routes/_app.groups": typeof import("./app/routes/_app.groups.tsx");
  "routes/_app.groups._index": typeof import("./app/routes/_app.groups._index.tsx");
  "routes/_app.groups.$id": typeof import("./app/routes/_app.groups.$id.tsx");
  "routes/_app.users": typeof import("./app/routes/_app.users.tsx");
  "routes/_app.users._index": typeof import("./app/routes/_app.users._index.tsx");
  "routes/_app.users.$id": typeof import("./app/routes/_app.users.$id.tsx");
  "routes/_app.apps": typeof import("./app/routes/_app.apps.tsx");
  "routes/_app.apps._index": typeof import("./app/routes/_app.apps._index.tsx");
};